Update fv3_physics.rst
Indicate the version of cartopy which works.  The planview plot will generate an error from cartopy crs if version 0.21 is used:

error in cartopy:
File "/d1/personal/mwin/miniconda3/envs/phys_tend/lib/python3.8/site-packages/cartopy/crs.py", line 1738, in init
n_parallels = len(standard_parallels)
TypeError: object of type 'NoneType' has no len()